FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update 
RUN apt-get upgrade -y
RUN apt-get autoremove -y
RUN apt-get install -y python3-pip python3-dev
RUN cd /usr/local/bin 
RUN ln -s /usr/bin/python3 python 
RUN pip3 install --upgrade pip
RUN apt-get install -y g++ 
RUN apt-get install -y curl
RUN apt-get install -y apt-transport-https
RUN curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB3E94ADBE1229CF
RUN apt-get update -y
RUN ACCEPT_EULA=Y apt-get install --allow-unauthenticated -y msodbcsql17
RUN ACCEPT_EULA=Y apt-get install --allow-unauthenticated -y mssql-tools
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
#RUN source ~/.bashrc
# optional: for unixODBC development headers
RUN ACCEPT_EULA=Y apt-get install --allow-unauthenticated -y unixodbc-dev

#copy all files from repo to docker image
WORKDIR /app
COPY . /app

#install python libraries
RUN pip3 --no-cache-dir install -r requirements.txt

#start flask server
WORKDIR /app
EXPOSE 5000
ENTRYPOINT ["python3"]
CMD ["application.py"]
